import type { CSSProperties } from 'react'

type Styles = Record<string, CSSProperties>

export const s: Styles = {
  page: {
    maxWidth: 640,
    margin: '0 auto',
    padding: '32px 16px 64px',
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
    minHeight: '100vh',
  },
  heading: {
    fontSize: 32,
    fontWeight: 800,
    letterSpacing: -1,
  },
  sub: {
    color: '#888',
    fontSize: 15,
  },
  dropZone: {
    border: '2px dashed #333',
    borderRadius: 16,
    padding: '48px 24px',
    textAlign: 'center',
    cursor: 'pointer',
    color: '#555',
    transition: 'border-color 0.2s, background 0.2s',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
  },
  dropZoneActive: {
    borderColor: '#E1306C',
    background: 'rgba(225,48,108,0.05)',
    color: '#E1306C',
  },
  dropIcon: {
    fontSize: 48,
    lineHeight: 1,
    color: '#444',
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 1fr)',
    gap: 8,
  },
  thumb: {
    position: 'relative',
    aspectRatio: '1',
    borderRadius: 8,
    overflow: 'hidden',
    background: '#111',
  },
  thumbMedia: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
  },
  badge: {
    position: 'absolute',
    top: 4,
    left: 6,
    background: 'rgba(0,0,0,0.7)',
    borderRadius: 4,
    padding: '1px 5px',
    fontSize: 12,
    fontWeight: 700,
  },
  vidBadge: {
    position: 'absolute',
    bottom: 6,
    left: 6,
    fontSize: 12,
    background: 'rgba(0,0,0,0.6)',
    borderRadius: 4,
    padding: '2px 6px',
  },
  removeBtn: {
    position: 'absolute',
    top: 4,
    right: 4,
    background: 'rgba(0,0,0,0.6)',
    border: 'none',
    color: '#fff',
    borderRadius: '50%',
    width: 22,
    height: 22,
    cursor: 'pointer',
    fontSize: 11,
    lineHeight: '22px',
    textAlign: 'center',
    padding: 0,
  },
  btnPrimary: {
    display: 'block',
    width: '100%',
    padding: '16px 24px',
    background: '#E1306C',
    color: '#fff',
    border: 'none',
    borderRadius: 12,
    fontSize: 17,
    fontWeight: 700,
    cursor: 'pointer',
    textAlign: 'center',
    textDecoration: 'none',
  },
  btnSecondary: {
    display: 'block',
    flex: 1,
    padding: '16px 24px',
    background: 'transparent',
    color: '#E1306C',
    border: '1.5px solid #E1306C',
    borderRadius: 12,
    fontSize: 17,
    fontWeight: 700,
    cursor: 'pointer',
    textAlign: 'center',
  },
  btnDisabled: {
    display: 'block',
    width: '100%',
    padding: '16px 24px',
    background: '#222',
    color: '#555',
    border: 'none',
    borderRadius: 12,
    fontSize: 17,
    fontWeight: 700,
    cursor: 'not-allowed',
    textAlign: 'center',
  },
  row: {
    display: 'flex',
    gap: 12,
  },
  video: {
    width: '100%',
    borderRadius: 12,
    background: '#111',
    maxHeight: '70vh',
  },
  center: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: '100vh',
  },
  card: {
    background: '#111',
    borderRadius: 20,
    padding: '40px 32px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 12,
    width: 300,
    border: '1px solid #222',
  },
  spinner: {
    width: 48,
    height: 48,
    border: '3px solid #333',
    borderTop: '3px solid #E1306C',
    borderRadius: '50%',
    animation: 'spin 0.8s linear infinite',
  },
  title: {
    fontSize: 20,
    fontWeight: 700,
  },
  pct: {
    color: '#E1306C',
    fontWeight: 700,
  },
  barTrack: {
    width: '100%',
    height: 6,
    background: '#333',
    borderRadius: 3,
    overflow: 'hidden',
  },
  barFill: {
    height: '100%',
    background: '#E1306C',
    borderRadius: 3,
    transition: 'width 0.3s',
  },
}
